config/routes.rb
# :nocov:
class ActionDispatch::Routing::Mapper
  def edit_step(name, opts = {}, &block)
    resource name,
             only:       opts.fetch(:only, [:edit, :update]),
             controller: name,
             path_names: { edit: '' } do; block.call if block_given?; end
  end

  def crud_step(name, opts = {})
    edit_step name, opts do
      resources only: opts.fetch(:only, [:edit, :update, :destroy]),
                controller: name,
                path_names: { edit: '' }
    end
  end

  def show_step(name)
    resource name,
             only:       [:show],
             controller: name
  end

  def edit_routes(path)
    get   path, action: :edit
    put   path, action: :update
    patch path, action: :update
  end
end
# :nocov:

Rails.application.routes.draw do
  constraints host: 'c100.service.justice.gov.uk' do
    get '/(*path)' => redirect(
      ShortUrlExpander.new('https://apply-to-court-about-child-arrangements.service.justice.gov.uk'), status: 302
    )
  end

  # Back office
  namespace :backoffice do
    get '/', to: 'auth0#index'

    # Sidekiq Web UI (when signed in)
    constraints ->(req) { req.session[:backoffice_userinfo].present? } do
      require 'sidekiq/web'
      Sidekiq::Web.set :sessions, false
      mount Sidekiq::Web => '/sidekiq'
    end

    # Sidekiq Web UI fallback when signed out
    get :sidekiq, to: redirect(path: '/backoffice', status: 307)

    namespace :auth0 do
      get :callback
      get :failure
      post :local_auth
      delete :logout
    end

    resources :users, only: [:index] do
      get :exists, on: :member, constraints: { id: /[^\/]+/ }
    end

    resource :errors, only: [] do
      get :unhandled
    end

    # Auth0-protected routes
    resources :dashboard, only: [:index] do
      post :lookup, on: :collection
      put :complete_application
    end

    resources :emails, only: [:index] do
      post :lookup, on: :collection
      put :resend
    end

    resources :audit, only: [:index]
  end

  devise_for :users,
             controllers: {
               registrations: 'users/registrations',
               passwords: 'users/passwords',
               sessions: 'users/logins'
             },
             path_names: {
               sign_in: 'login',
               sign_out: 'logout'
             }

  namespace :users do
    devise_scope :user do
      get 'login/logged_out',        to: 'logins#logged_out'
      get 'login/save_confirmation', to: 'logins#save_confirmation'

      get 'password/reset_sent',         to: 'passwords#reset_sent'
      get 'password/reset_confirmation', to: 'passwords#reset_confirmation'

      get 'registration/save_confirmation',   to: 'registrations#save_confirmation'
      get 'registration/update_confirmation', to: 'registrations#update_confirmation'
    end

    resources :drafts, only: [:index, :destroy] do
      get :resume, on: :member
    end
  end

  namespace :steps do
    namespace :opening do
      show_step :start
      show_step :warning
      edit_step :postcode
      show_step :error_but_continue
      show_step :no_court_found
      edit_step :research_consent
      edit_step :consent_order
      show_step :consent_order_sought
      edit_step :child_protection_cases
      show_step :child_protection_info
    end
    namespace :application do
      edit_step :previous_proceedings
      edit_step :court_proceedings
      edit_step :urgent_hearing
      edit_step :urgent_hearing_details
      edit_step :without_notice
      edit_step :without_notice_details
      edit_step :permission_sought
      edit_step :permission_details
      edit_step :details
      edit_step :litigation_capacity
      edit_step :litigation_capacity_details
      edit_step :submission
      show_step :receipt_email_check
      edit_step :payment
      edit_step :check_your_answers do
        get :resume, action: :resume
      end
    end
    namespace :petition do
      edit_step :orders
      show_step :playback
      edit_step :protection
    end
    namespace :miam do
      edit_step :acknowledgement
      edit_step :attended
      edit_step :mediator_exemption
      edit_step :exemption_claim
      edit_step :certification
      show_step :certification_exit
      edit_step :certification_date
      edit_step :certification_details
      show_step :certification_confirmation
    end
    namespace :miam_exemptions do
      edit_step :domestic
      edit_step :protection
      edit_step :urgency
      edit_step :adr
      edit_step :misc
      show_step :reasons_playback
      show_step :safety_playback
      show_step :exit_page
    end
    namespace :abduction do
      edit_step :international
      edit_step :children_have_passport
      edit_step :passport_details
      edit_step :previous_attempt
      edit_step :previous_attempt_details
      edit_step :risk_details
    end
    namespace :safety_questions do
      show_step :start
      edit_step :address_confidentiality
      edit_step :risk_of_abduction
      edit_step :substance_abuse
      edit_step :children_abuse
      edit_step :domestic_abuse
      edit_step :other_abuse
    end
    namespace :abuse_concerns do
      show_step :start
      show_step :children_info
      show_step :applicant_info
      edit_step :question do
        get '/:subject/:kind', action: :edit
      end
      edit_step :details do
        get '/:subject/:kind', action: :edit
      end
      edit_step :contact
    end
    namespace :court_orders do
      edit_step :has_orders
      edit_step :details
    end
    namespace :alternatives do
      show_step :start
      edit_step :negotiation_tools
      edit_step :mediation
      edit_step :lawyer_negotiation
      edit_step :collaborative_law
      edit_step :court
    end
    namespace :address do
      crud_step :lookup, only: [:edit, :update]
      crud_step :results, only: [:edit, :update]
    end
    namespace :children do
      crud_step :names
      crud_step :personal_details, only: [:edit, :update]
      crud_step :orders, only: [:edit, :update]
      crud_step :special_guardianship_order, only: [:edit, :update]
      edit_step :additional_details
      edit_step :has_other_children
      crud_step :residence, only: [:edit, :update]
    end
    namespace :other_children do
      crud_step :names
      crud_step :personal_details, only: [:edit, :update]
    end
    namespace :applicant do
      crud_step :names
      crud_step :personal_details, only: [:edit, :update]
      crud_step :under_age,        only: [:edit, :update]
      crud_step :contact_details,  only: [:edit, :update]
      crud_step :address_details,  only: [:edit, :update]
      edit_step :has_solicitor
      edit_step :relationship, only: [] do
        edit_routes ':id/child/:child_id'
      end
    end
    namespace :solicitor do
      edit_step :personal_details
      edit_step :address_details
      edit_step :contact_details
    end
    namespace :respondent do
      crud_step :names
      crud_step :personal_details, only: [:edit, :update]
      crud_step :contact_details,  only: [:edit, :update]
      crud_step :address_details,  only: [:edit, :update]
      edit_step :has_other_parties
      edit_step :relationship, only: [] do
        edit_routes ':id/child/:child_id'
      end
    end
    namespace :other_party do
      crud_step :names
      crud_step :personal_details, only: [:edit, :update]
      crud_step :address_details,  only: [:edit, :update]
      edit_step :relationship, only: [] do
        edit_routes ':id/child/:child_id'
      end
    end
    namespace :permission do
      namespace :question, path: ':question_name' do
        edit_routes 'relationship/:relationship_id'
      end
    end
    namespace :international do
      edit_step :resident
      edit_step :jurisdiction
      edit_step :request
    end
    namespace :attending_court do
      edit_step :language
      edit_step :intermediary
      edit_step :special_arrangements
      edit_step :special_assistance
    end
    namespace :completion do
      show_step :confirmation
      show_step :what_next
      show_step :summary
      # The following is an alias of the `what_next` route, for analytics tracking
      get :how_to_submit, to: 'what_next#show'
    end
  end

  resource :session, only: [:destroy] do
    member do
      get :ping
      post :bypass_postcode
      post :bypass_to_cya
    end
  end

  resource :callbacks, only: [] do
    post :notify
  end

  resources :payments, only: [] do
    get :validate, on: :member
  end

  resource :errors, only: [] do
    get :invalid_session
    get :application_not_found
    get :application_screening
    get :application_completed
    get :payment_error
    get :unhandled
    get :not_found
  end

  resource :cookies,
           path: '/about/cookies',
           path_names: { edit: '/' },
           only: [:edit, :update, :create]

  root 'steps/opening/start#show'

  get 'about/accessibility'
  get 'about/contact'
  get 'about/privacy'
  get 'about/terms_and_conditions'
  get 'about/privacy_consent'
  get 'about/miam_exemptions'

  # This route is used in court emails to point users to the survey
  get :survey, to: redirect(Rails.configuration.surveys[:success], status: 302)

  # Health and ping endpoints (`status` and `health` are alias)
  defaults format: :json do
    get :status, to: 'status#index'
    get :health, to: 'status#index'
    get :ping,   to: 'status#ping'
  end

  # catch-all route
  # :nocov:
  match '*path', to: 'errors#not_found', via: :all, constraints:
    lambda { |_request| !Rails.application.config.consider_all_requests_local }
  # :nocov:
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def accessibility; end

  def contact; end

  def privacy; end

  def terms_and_conditions; end

  def privacy_consent; end

  def miam_exemptions; end
end

app/views/about/accessibility.en.html.erb
<% title 'Accessibility' %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-xl">Accessibility</h1>

    <h2 class="govuk-heading-l">Using this online service</h2>

    <p class="govuk-body">
      This online service is run by the Ministry of Justice. We want as many people as possible to be able to use it.
    </p>

    <p class="govuk-body">For example, that means you should be able to:</p>

    <ul class="govuk-list govuk-list--bullet">
      <li>change colours, contrast levels and fonts</li>
      <li>zoom in up to 300% without the text spilling off the screen</li>
      <li>navigate most of the online service using just a keyboard</li>
      <li>navigate most of the online service using speech recognition software</li>
      <li>listen to most of the online service using a screen reader (including the most recent versions of JAWS, NVDA and VoiceOver)</li>
    </ul>

    <p class="govuk-body">We’ve also made the text as simple as possible to understand.</p>

    <p class="govuk-body">
      <a href="https://mcmw.abilitynet.org.uk/" class="govuk-link" rel="external" target="_blank">AbilityNet</a> has
      advice on making your device easier to use if you have a disability.
    </p>

    <h2 class="govuk-heading-l">About the accessibility of this online service</h2>

    <p class="govuk-body">
      Basic tests were performed on this online service on 15 May 2020. These tests were carried out by the Ministry of Justice.
    </p>

    <p class="govuk-body">
      We tested the start page, the login page and the contact page, as well as the privacy policy and the terms and
      conditions.
    </p>

    <p class="govuk-body">We also tested the stages of the service that require different types of user interaction:</p>

    <ul class="govuk-list govuk-list--bullet">
      <li>inputting text</li>
      <li>inputting numbers</li>
      <li>using radio buttons</li>
      <li>using check boxes</li>
      <li>following links for support</li>
      <li>finding an address by searching for a postcode</li>
      <li>reviewing answers</li>
    </ul>

    <p class="govuk-body">Finally, we tested cookies and the third-party supplier feedback survey page.</p>

    <h2 class="govuk-heading-l">What to do if you cannot access parts of this online service</h2>

    <p class="govuk-body">
      If you need information on this online service in a different format like an accessible PDF, large print, easy
      read, audio recording or braille, email
      <a href="mailto:c100helpdesk@digital.justice.gov.uk?subject=Accessibility" class="govuk-link ga-clickAction" data-ga-category="accessibility" data-ga-action="click" data-ga-label="mailto helpdesk">c100helpdesk@digital.justice.gov.uk</a>.
    </p>

    <h2 class="govuk-heading-l">Technical information about accessibility for this online service</h2>

    <p class="govuk-body">
      The Ministry of Justice is committed to making its website accessible, in accordance with the Public Sector Bodies
      (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018.
    </p>

    <p class="govuk-body">
      This online service is partially compliant with the
      <a href="https://www.w3.org/TR/WCAG21/" class="govuk-link" rel="external" target="_blank">Web Content
        Accessibility Guidelines version 2.1</a> AA standard, due to the non-compliances listed below.
    </p>

    <h2 class="govuk-heading-l">Non compliance with the accessibility regulations</h2>

    <p class="govuk-body">
      Some pages may be non-accessible where further inputs are revealed based on a checkbox or radio selection. We’re
      working to understand whether these nested inputs are fully accessible.
    </p>

    <p class="govuk-body">We plan to resolve this issue by September 2020.</p>

    <h2 class="govuk-heading-l">PDF content</h2>

    <p class="govuk-body">
      Some PDF content is essential to providing our services, but may not yet meet accessibility standards for screen
      readers. The PDF content is designed to be used by the courts and is built to their specification, so any changes
      will require their input. We plan to review this content by September 2020.
    </p>

    <h2 class="govuk-heading-l">Third-party supplied service</h2>

    <p class="govuk-body">This online service uses a third-party supplied service to collect feedback.</p>

    <p class="govuk-body">
      This third-party supplied service is “skinned” to look like our website, but part of it does not meet
      <a href="https://www.w3.org/TR/WCAG21/" class="govuk-link" rel="external" target="_blank">Web Content
        Accessibility Guidelines version 2.1</a> standards because clicking the labels does not move the cursor into the
      corresponding text area.
    </p>

    <p class="govuk-body">
      The third-party supplied feedback form is one part of our overall approach to collecting feedback. We'll continue
      to carry out further testing as we develop the service and we plan to reassess the feedback form by September
      2020.
    </p>

    <h2 class="govuk-heading-l">Reporting accessibility problems</h2>

    <p class="govuk-body">
      We’re always looking to improve the accessibility of this online service. If you find any problems not listed on
      this page or you think we’re not meeting accessibility requirements, contact
      <a href="mailto:c100helpdesk@digital.justice.gov.uk?subject=Accessibility" class="govuk-link ga-clickAction" data-ga-category="accessibility" data-ga-action="click" data-ga-label="mailto helpdesk">c100helpdesk@digital.justice.gov.uk</a>.
    </p>

    <h2 class="govuk-heading-l">Enforcement procedure</h2>

    <p class="govuk-body">
      The Equality and Human Rights Commission (EHRC) is responsible for enforcing the Public Sector Bodies (Websites
      and Mobile Applications) (No. 2) Accessibility Regulations 2018 (the ‘accessibility regulations’). If you’re not
      happy with how we respond to your complaint,
      <a href="https://www.equalityadvisoryservice.com/" class="govuk-link" rel="external" target="_blank">contact the
        Equality Advisory and Support Service (EASS)</a>.
    </p>

    <p class="govuk-body govuk-!-margin-top-8">
      This statement was prepared on 19 November 2019.<br/>It was last updated on 21 May 2020.
    </p>
  </div>
</div>

app/views/about/contact.en.html.erb
<% title 'Contact' %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-xl">Get in touch</h1>

    <p class="govuk-body">
      If you’d like to report a problem or have a suggestion to help improve this service for others, get in touch by
      sending an email to:
    </p>

    <p class="govuk-body-l">
      <a href="mailto:c100helpdesk@digital.justice.gov.uk?subject=Feedback" class="govuk-link ga-clickAction" data-ga-category="feedback" data-ga-action="click" data-ga-label="report a problem">c100helpdesk@digital.justice.gov.uk</a>
    </p>

    <p class="govuk-body">This email address should only be used for feedback on the digital service.</p>

    <p class="govuk-body">
      We cannot answer any questions about applications that have already been submitted. You can
      <a href="https://www.find-court-tribunal.service.gov.uk/services/childcare-and-parenting/childcare-arrangements/search-by-postcode" class="govuk-link" rel="external" target="_blank">contact
        the relevant court</a> if you need to discuss your case.
    </p>
  </div>
</div>

app/views/about/privacy_consent.en.html.erb
<% title 'Being contacted about your experience of using this service' %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-xl">Being contacted about your experience of using this service</h1>

    <p class="govuk-body">By choosing to be contacted by the Ministry of Justice (MOJ) you agree that your personal details and any
      information you give can be used by MOJ for research purposes.</p>

    <h2 class="govuk-heading-l">The information we use</h2>

    <p class="govuk-body">MOJ can use any information you provide, including your name and contact information (such as your email
      address).</p>

    <h2 class="govuk-heading-l">Why we use this information</h2>

    <p class="govuk-body">To get your thoughts on MOJ services - for example, we might send you satisfaction surveys.</p>

    <h2 class="govuk-heading-l">How long we will keep your data</h2>

    <p class="govuk-body">If you choose to be contacted by MOJ about your experience of using this service, your personal information
      will be kept for 2 years.</p>

    <p class="govuk-body">You can also choose to be contacted for other MOJ research. If you opt in, only your name and contact details
      will be shared with the MOJ research team.</p>

    <h2 class="govuk-heading-l">Your rights</h2>

    <p class="govuk-body">You have the right to:</p>

    <ul class="govuk-list govuk-list--bullet">
      <li>access the personal information MOJ holds about you</li>
      <li>change any incorrect information MOJ holds about you</li>
      <li>stop MOJ using your personal information</li>
    </ul>

    <p class="govuk-body">If you have chosen to be contacted about your experience of using this service, you have the right to request
      that your personal information is:</p>

    <ul class="govuk-list govuk-list--bullet">
      <li>deleted (the ‘right to be forgotten’)</li>
      <li>subject to restricted processing (MOJ can store your personal data, but not use it)</li>
      <li>transferred to you or another organisation in a commonly structured format (the ‘right to portability’)</li>
    </ul>

    <p class="govuk-body">Some of these rights only apply in certain circumstances. Even if you want to exercise them, MOJ may not be
      required to comply.</p>

    <h2 class="govuk-heading-l">Withdrawing your consent to be
      contacted</h2>

    <p class="govuk-body">You have the right to withdraw your consent at any time by emailing your request to
      <a href="mailto:data.compliance@justice.gov.uk" class="ga-clickAction govuk-link" data-ga-category="privacy"
         data-ga-action="click" data-ga-label="mailto data compliance">data.compliance@justice.gov.uk</a>.
    </p>

    <p class="govuk-body">The withdrawal of consent will not affect the lawfulness of processing based on consent before its
      withdrawal.</p>

    <h2 class="govuk-heading-l">Contacting MOJ</h2>

    <p class="govuk-body">You can contact MOJ if you:</p>

    <ul class="govuk-list govuk-list--bullet">
      <li>would like to update information MOJ holds about you</li>
      <li>want to exercise any of your rights</li>
      <li>have any questions about how MOJ handles your personal information</li>
    </ul>

    <p class="govuk-body">Send your request to MOJ by:</p>

    <ul class="govuk-list govuk-list--bullet">
      <li>email at
        <a href="mailto:data.compliance@justice.gov.uk" class="ga-clickAction govuk-link" data-ga-category="privacy"
           data-ga-action="click" data-ga-label="mailto data compliance">data.compliance@justice.gov.uk</a>
      </li>
      <li>post to Data Protection Officer, Ministry of Justice, 102 Petty France, London SW1H 9AJ</li>
    </ul>
  </div>
</div>

app/views/about/terms_and_conditions.en.html.erb
<% title 'Terms and conditions' %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-xl">Terms and conditions</h1>

    <p class="govuk-body-l">By using this service you agree to these terms and conditions.</p>

    <h2 class="govuk-heading-l">Responsibility for the service</h2>

    <p class="govuk-body">The Ministry of Justice (MOJ) runs this service.</p>
    <p class="govuk-body">We try to make sure the information we provide is accurate and complete and the service is always available and virus free.</p>
    <p class="govuk-body">The MoJ accepts no liability for:</p>

    <ul class="govuk-list govuk-list--bullet">
      <li>you being unable to access the service (for example due to high demand or because we've taken it down for maintenance)</li>
      <li>indirect damages arising from you using the service or relying on its content</li>
      <li>the content and availability of external websites that link to the service or which link from it</li>
    </ul>

    <h2 class="govuk-heading-l">Information about you and your visits</h2>

    <p class="govuk-body">We collect information about you in accordance with
      our <%= link_to 'privacy policy', about_privacy_path, class: 'ga-pageLink govuk-link', data: {ga_category: 'footer', ga_label: 'privacy'} %>
      and our <%= link_to 'cookie policy', edit_cookies_path, class: 'ga-pageLink govuk-link', data: {ga_category: 'footer', ga_label: 'cookies'} %>.
      By using this service you agree to us collecting this information and confirm that any data you provide is accurate.</p>

    <h2 class="govuk-heading-l">Scotland and Northern Ireland</h2>

    <p class="govuk-body">Some parts of this service only apply to England and Wales.</p>
    <p class="govuk-body">For example, if you want to go to court the process is different in
      <a href="https://www.mygov.scot/crime-justice-and-the-law/courts-and-sentencing" class="govuk-link" rel="external" target="_blank">Scotland</a> and
      <a href="https://www.nidirect.gov.uk/articles/solicitors-and-courts" class="govuk-link" rel="external" target="_blank">Northern Ireland</a>.
    </p>
  </div>
</div>